! This subroutine allocates memory for all arrays.
! ***********************************************
subroutine allocateMemoryForArrays()
use variablesDeclaration
implicit none

allocate(X(m,n))
allocate(Y(m,n))
allocate(cellVolume(m-1,n-1))
allocate(x0fCellCentroid(m-1,n-1))
allocate(y0fCellCentroid(m-1,n-1))
allocate(x0fHorFaceCenter(m-1,n))
allocate(y0fHorFaceCenter(m-1,n))
allocate(x0fVerFaceCenter(m,n-1))
allocate(y0fVerFaceCenter(m,n-1))
allocate(EastGeomFactor(m-1,n-1))
allocate(WestGeomFactor(m-1,n-1))
allocate(NorthGeomFactor(m-1,n-1))
allocate(SouthGeomFactor(m-1,n-1))
allocate(horFaceArea(m-1,n))
allocate(verFaceArea(m,n-1))
allocate(x0fUnitSe(m,n-1))
allocate(y0fUnitSe(m,n-1))
allocate(x0fUnitEe(m,n-1))
allocate(y0fUnitEe(m,n-1))
allocate(x0fUnitTe(m,n-1))
allocate(y0fUnitTe(m,n-1))
allocate(x0fUnitSn(m-1,n))
allocate(y0fUnitSn(m-1,n))
allocate(x0fUnitEn(m-1,n))
allocate(y0fUnitEn(m-1,n))
allocate(x0fUnitTn(m-1,n))
allocate(y0fUnitTn(m-1,n))
allocate(normEe(m,n-1))
allocate(normTe(m,n-1))
allocate(normEn(m-1,n))
allocate(normTn(m-1,n))
allocate(horFaceDensity(m-1,n))
allocate(verFaceDensity(m,n-1))
allocate(x0fHorVelocity(m-1,n))
allocate(y0fHorVelocity(m-1,n))
allocate(x0fVerVelocity(m,n-1))
allocate(y0fVerVelocity(m,n-1))
allocate(sourceField(m-1,n-1))
allocate(md0tH0rP0sDir(m-1,n),md0tVerP0sDir(m,n-1))
allocate(aE(m-1,n-1),aW(m-1,n-1),aS(m-1,n-1),aN(m-1,n-1),bC(m-1,n-1),aC(m-1,n-1))
allocate(phi(m-1,n-1),phiNew(m-1,n-1))
allocate(ldVerSweep(n-1),mdVerSweep(n-1),udVerSweep(n-1),sourceVerSweep(n-1))
allocate(ldHorSweep(m-1),mdHorSweep(m-1),udHorSweep(m-1),sourceHorSweep(m-1))
allocate(md0tePhie(m-1,n-1),md0tnPhin(m-1,n-1),md0twPhiw(m-1,n-1),md0tsPhis(m-1,n-1))
allocate(md0tePhieSmart(m-1,n-1),md0tnPhinSmart(m-1,n-1),md0twPhiwSmart(m-1,n-1),md0tsPhisSmart(m-1,n-1))
allocate(x0fGradientAtCell(m-1,n-1),y0fGradientAtCell(m-1,n-1))
allocate(horInterfaceDiff(m-1,n),verInterfaceDiff(m,n-1),gammaField(m-1,n-1))

allocate(outletConditionNorth(m-1))
allocate(outletConditionEast(n-1))
allocate(outletConditionSouth(m-1))
allocate(outletConditionWest(n-1))
allocate(inletConditionNorth(m-1))
allocate(inletConditionEast(n-1))
allocate(inletConditionSouth(m-1))
allocate(inletConditionWest(n-1))
allocate(wallConditionNorth(m-1))
allocate(wallConditionEast(n-1))
allocate(wallConditionSouth(m-1))
allocate(wallConditionWest(n-1))
allocate(phiAtInletNorth(m-1))
allocate(phiAtInletSouth(m-1))
allocate(phiAtInletEast(n-1))
allocate(phiAtInletWest(n-1))
allocate(dirichletNorth(m-1))
allocate(dirichletEast(n-1))
allocate(dirichletSouth(m-1))
allocate(dirichletWest(n-1))
allocate(dirichletValueNorth(m-1))
allocate(dirichletValueEast(n-1))
allocate(dirichletValueSouth(m-1))
allocate(dirichletValueWest(n-1))
allocate(vonNeumannNorth(m-1))
allocate(vonNeumannEast(n-1))
allocate(vonNeumannSouth(m-1))
allocate(vonNeumannWest(n-1))
allocate(x0fNeumannGradNorth(m-1))
allocate(x0fNeumannGradEast(n-1))
allocate(x0fNeumannGradSouth(m-1)) 
allocate(x0fNeumannGradWest(n-1))
allocate(y0fNeumannGradNorth(m-1))
allocate(y0fNeumannGradEast(n-1))
allocate(y0fNeumannGradSouth(m-1))
allocate(y0fNeumannGradWest(n-1))
allocate(robinNorth(m-1))
allocate(robinEast(n-1))
allocate(robinSouth(m-1))
allocate(robinWest(n-1))
allocate(phiInfNorth(m-1))
allocate(phiInfEast(n-1))
allocate(phiInfSouth(m-1))
allocate(phiInfWest(n-1))
allocate(hInfNorth(m-1))
allocate(hInfEast(n-1))
allocate(hInfSouth(m-1))
allocate(hInfWest(n-1))

allocate(u(m-1,n-1),uNew(m-1,n-1))
allocate(v(m-1,n-1),vNew(m-1,n-1))
allocate(initialp(m-1,n-1),p(m-1,n-1))

allocate(uAtInletSouth(m-1))
allocate(vAtInletSouth(m-1))
allocate(uAtInletNorth(m-1))
allocate(vAtInletNorth(m-1))
allocate(uAtInletEast(n-1))
allocate(vAtInletEast(n-1))
allocate(uAtInletWest(n-1))
allocate(vAtInletWest(n-1))

allocate(x0fGradp(m-1,n-1),x0fGradu(m-1,n-1),y0fGradu(m-1,n-1),y0fGradp(m-1,n-1))
allocate(x0fGradv(m-1,n-1),y0fGradv(m-1,n-1))
allocate(pCorrection(m-1,n-1),pCorrectionNew(m-1,n-1),initialu(m-1,n-1),initialv(m-1,n-1))
allocate(uCorrection(m-1,n-1),uCorrectionNew(m-1,n-1),vCorrection(m-1,n-1),vCorrectionNew(m-1,n-1))
allocate(md0teue(m-1,n-1),md0tnun(m-1,n-1),md0twuw(m-1,n-1),md0tsus(m-1,n-1))
allocate(md0teueSmart(m-1,n-1),md0tnunSmart(m-1,n-1),md0twuwSmart(m-1,n-1),md0tsusSmart(m-1,n-1))

allocate(md0teve(m-1,n-1),md0tnvn(m-1,n-1),md0twvw(m-1,n-1),md0tsvs(m-1,n-1))
allocate(md0teveSmart(m-1,n-1),md0tnvnSmart(m-1,n-1),md0twvwSmart(m-1,n-1),md0tsvsSmart(m-1,n-1))

allocate(aEu(m-1,n-1),aWu(m-1,n-1),aSu(m-1,n-1),aNu(m-1,n-1),bCu(m-1,n-1),aCu(m-1,n-1))
allocate(aEv(m-1,n-1),aWv(m-1,n-1),aSv(m-1,n-1),aNv(m-1,n-1),bCv(m-1,n-1),aCv(m-1,n-1))
end subroutine 
